version: '3.8'

services:
  web:
    build: .
    container_name: flask_crud
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_USER=admin
      - DB_PASSWORD=wolfpassword123
      - DB_NAME=inventory
    command: flask run --host=0.0.0.0 --port=5000
